name: my_notes

description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For ios icons
  cupertino_icons: ^1.0.6

  # For state management
  provider: ^6.1.1

  # For showing toast
  fluttertoast: ^8.2.4

  # For showing animated text
  animated_text_kit: ^4.2.2

  # For firebase services
  firebase_core: ^2.24.2

  # For firebase services
  firebase_auth: ^4.15.3

  # For firebase services
  cloud_firestore: ^4.13.6

  # For firebase services
  firebase_storage: ^11.5.6

  # For finding the paths
  path_provider: ^2.1.1

  # For merging the paths
  path: ^1.8.3

  # For selecting images
  image_picker: ^1.0.5

  # For sharing selected texts
  share_plus: ^8.0.2

  # For state management
  bloc: ^8.1.2

  # For state management
  flutter_bloc: ^8.1.3

  # For comparison
  equatable: ^2.0.5

  # For date formatting
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/project.png
    - assets/icon/icon.png

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
